name: Deploy to production
on:
  release:
    types: [published]

jobs:
  release-production:
    name: Release to Production
    if: startsWith(github.ref_name, 'rel-') # the prefix we have added to the tag
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        run: |
          echo "aws-actions/configure-aws-credentials@v1"
      - name: Deploy to production
        uses: ./.github/workflows/deploy-env/composite
        with:
          env: "production"
          image_tag: "${{ github.ref_name }}"

      - name: Health-check failure
        id: deploy-prod
        continue-on-error: true
        run: exit 0

      - name: Rollback to last successful release
        if: steps.deploy-prod.outcome == 'failure'
        env:
          GITHUB_API_VERSION: "X-GitHub-Api-Version: 2022-11-28"
          ACCEPT_HEADER: "Accept: application/vnd.github+json"
          GITHUB_API_BASE_URL: "https://api.github.com/repos/ojleorg/web-app" 
        run: |
          LAST_SUCCESSFUL_RUN_ID=$(curl -s -L \
            -H "${{env.ACCEPT_HEADER}}" \
            -H "Authorization: Bearer ${{secrets.GH_TOK}}" \
            -H "${{env.GITHUB_API_VERSION}}" \
            ${{env.GITHUB_API_BASE_URL}}/actions/workflows/deploy-production.yaml/runs \
            | jq 'first(.workflow_runs[] | select(.conclusion == "success") | .id)')

          LAST_SUCCESSFUL_RUN_TAG_NAME=$(curl -s -L \
            -H "${{env.ACCEPT_HEADER}}" \
            -H "Authorization: Bearer ${{secrets.GH_TOK}}" \
            -H "${{env.GITHUB_API_VERSION}}" \
            ${{env.GITHUB_API_BASE_URL}}/actions/workflows/deploy-production.yaml/runs \
            | jq -r 'first(.workflow_runs[] | select(.conclusion == "success") | .head_branch)')

          LAST_SUCCESSFUL_RELEASE_ID=$(curl -s -L \
            -H "${{env.ACCEPT_HEADER}}" \
            -H "Authorization: Bearer ${{secrets.GH_TOK}}" \
            -H "${{env.GITHUB_API_VERSION}}" \
            ${{env.GITHUB_API_BASE_URL}}/releases \
            | jq --arg TAG_NAME "${LAST_SUCCESSFUL_RUN_TAG_NAME}" '.[] | select(.tag_name==$TAG_NAME).id')
          
          # Re-run last successful release workflow  
          curl -s -L \
            -X POST \
            -H "${{env.ACCEPT_HEADER}}" \
            -H "Authorization: Bearer ${{secrets.GH_TOK}}" \
            -H "${{env.GITHUB_API_VERSION}}" \
            ${{env.GITHUB_API_BASE_URL}}/actions/runs/${LAST_SUCCESSFUL_RUN_ID}/rerun
            
          # Re-set last successful release as 'latest'
          curl -s -L \
            -X PATCH \
            -H "${{env.ACCEPT_HEADER}}" \
            -H "Authorization: Bearer ${{secrets.GH_TOK}}" \
            -H "${{env.GITHUB_API_VERSION}}" \
            ${{env.GITHUB_API_BASE_URL}}/releases/${LAST_SUCCESSFUL_RELEASE_ID} \
            -d '{"make_latest":"true"}'
